### ISSUE TITLE
Executable `/usr/bin/ruby2.5` not found

### ISSUE THREAD

**Issue by uriva** [markdownlint/markdownlint#352]
Is this supposed to work with any ruby version or I need to install a specific one?

Here is my setup:

```
$ ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
```
pre-commit config:
```
repos:
  - repo: https://github.com/markdownlint/markdownlint
    rev: master
    hooks:
      - id: markdownlint
        entry: mdl --style markdownlint.rb
```

When committing, I get:
```
Markdownlint.............................................................Failed
- hook id: markdownlint
- exit code: 1

Executable `/usr/bin/ruby2.5` not found
```
